nodeLinker: node-modules

npmAuthToken: "${YARN_NPM_AUTH_TOKEN:-}"

npmRegistryServer: "https://repox.jfrog.io/artifactory/api/npm/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
