nodeLinker: node-modules

npmAuthToken: "reftkn:01:1799490028:sqDqjQVmZbsdoCTLOtT6wBEkIbR"

npmRegistryServer: "https://repox.jfrog.io/artifactory/api/npm/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
